version: '1'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/node_modules

volumes:
  node_modules:
    